# themes from https://github.com/alacritty/alacritty-theme

[general]
import = ["~/.config/alacritty/themes/themes/zenburn.toml"]

[terminal.shell]
program = "/usr/bin/tmux"
#program = "/bin/bash"
#args = ["-l"]

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 11

[font.normal]
family = "Jetbrains Mono"

[window]
startup_mode = "Maximized"
decorations = "none"

[window.padding]
x = 7
y = 0

[mouse]
hide_when_typing = true
